---
title: "DASHBOARD"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(forecast)
library(dygraphs)
library(knitr)
library(zoo)
library(plyr)
library(dplyr)
library(lubridate)
library(plotly)
library(vcd)
library(ggmap)
library(maps)
library(reshape2)


###### df1
df1 <- read.table("~/Desktop/R/R-ladies/Flex_dashboard_2/df1.csv", sep=",", header = T)
colnames(df1)
df1$X <-NULL
str(df1)
df1$date <- as.Date(as.character(df1$date))

sessions<- sum(df1$sessions)
sessions <- format(sessions,big.mark = ".", scientific=FALSE)
revenue <- round(sum(df1$transactionRevenue),0)
revenue <- format(revenue,big.mark = ".", scientific=FALSE)

ssbyday <- ddply(df1, .(date), summarize, total = sum(sessions))
revbyday <- ddply(df1, .(date), summarize, total = round(sum(transactionRevenue),0))

itemby <- ddply(df1, .(dimension1), summarize, total = sum(transactions))
str(itemby)
itembyuser <- itemby[!(apply(itemby, 1, function(y) any(y == 0))),]
mytable2 <- table(itembyuser)
margin.table(mytable2, 2)

topusers <- itembyuser %>% arrange(desc(total)) %>% top_n(20)


###### df2
df2 <- read.table("~/Desktop/R/R-ladies/Flex_dashboard_2/df2.csv", sep=",", header = T)
colnames(df2)
df2$X <-NULL
str(df2)
df2$date <- as.Date(as.character(df2$date))
cityinfo <- ddply(df2, .(city), summarize, total = sum(transactions))
cityinfo2 <- cityinfo %>% arrange(desc(total)) %>% filter(!(city=="(not set)")) %>% top_n(20)
cityinfo3 <- cityinfo2


###### df3
df3 <- read.table("~/Desktop/R/R-ladies/Flex_dashboard_2/df3.csv", sep=",", header = T)
colnames(df3)
df3$X <-NULL


###### df4
df4 <- read.table("~/Desktop/R/R-ladies/Flex_dashboard_2/df4.csv", sep=",", header = T)
colnames(df4)
df4$X <-NULL
str(df4)
df4$transactionId <- as.factor(df4$transactionId)
mytable <- table(df4)
margin.table(mytable, 2)
  

###### df5
df5 <- read.table("~/Desktop/R/R-ladies/Flex_dashboard_2/df5.csv", sep=",", header = T)
colnames(df5)
df5$X <-NULL
str(df5)
summary(df5)
df5$revenuePerTransaction <- round(df5$revenuePerTransaction)
intv <- c(0,100,300,500,1000,1500,2000,4000,6000)
df5$intev.rev <- cut(df5$revenuePerTransaction, breaks=intv, include.lowest = T)
mytable2 <- table(df5)
margin.table(mytable2, 3)


###### df6
df6 <- read.table("~/Desktop/R/R-ladies/Flex_dashboard_2/df6.csv", sep=",", header = T)
df6$X <-NULL
df6$date <- as.Date(as.character(df6$date))
data.evol <- melt(df6,id="date")

```

Sidebar {.sidebar}
=====================================


The following Dashboard show a quick overview of the business of A Ecommerce.


Data source: Google Analytics
Date Range: January 01, 2016 to December 31, 2016




Global {data-icon="fa-globe"} 
===================================== 

Row 
-----------------------------------------------------------------------

### Traffic 


```{r}
valueBox(sessions, icon = "ion-person-stalker")
```

### Revenue 

```{r}
valueBox(revenue, icon = "ion-card")
```




Row 
-----------------------------------------------------------------------

### Traffic Evolution 

```{r}
a <- ggplot(ssbyday, aes(date, total)) + 
        geom_line()+
        theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.y = element_blank())

ggplotly(a)

```



### Revenue Evolution 

```{r}

b <- ggplot(revbyday, aes(date, total)) + 
  geom_line() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())


ggplotly(b)
```



Row 
-----------------------------------------------------------------------

### Traffic Channel Box Plot

```{r}

c <- ggplot(df1, aes(x=channelGrouping, y=sessions)) +
     geom_boxplot() +
     coord_flip()+
     theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_blank())
   

ggplotly(c)
```

### Average Price Per Transaction

```{r}

d <- ggplot(df5, aes(x=intev.rev)) + 
        geom_bar(stat="count") +
        coord_flip()+
        theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_blank())

ggplotly(d)

```



Shopping Behaviour {data-icon="fa-shopping-bag"}
=====================================

Column
-------------------------------------

### Transactions by User

```{r}

e <- ggplot(itembyuser, aes(total)) + 
        geom_histogram(binwidth = 1, colour="white", fill="black") +
        coord_flip()+
        theme(
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.ticks.y = element_blank())+
          scale_x_continuous(breaks=c(1,2,3,4,5,6))

ggplotly(e)

```


### ItemQuantity by Transaction

```{r}

f <- ggplot(df4, aes(itemQuantity)) + 
        geom_histogram(binwidth = 1, colour="white", fill="black") +
        coord_flip()+
        theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank())+
        scale_x_continuous(breaks=c(1,5,10,15,20,25,30,40,50,60))

ggplotly(f)

```



Row
-------------------------------------

### Transactions vs ItemQuantity Evolution

```{r}

g <- ggplot(data.evol, aes(date,value,colour=variable)) + 
        geom_line()+
        theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.y = element_blank())

ggplotly(g)

```
